## Aggregating Data

In [1]:
import pandas as pd

In [3]:
bios=pd.read_csv('./data/bios.csv')

In [4]:
bios.head()

,Unnamed: 0.1,Unnamed: 0,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,0,0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,1,1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,2,2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,3,3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,4,4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert

In [7]:
bios["born_city"].value_counts().tail()

born_city
Tsivilsk            1
Roth                1
Romoos              1
Dva Polya Artash    1
Dulwich Hill        1
Name: count, dtype: int64

In [8]:
bios[bios["born_country"]=='IND']["born_region"].value_counts()

born_region
Punjab                                 94
Maharashtra                            56
West Bengal                            49
Haryana                                43
Uttar Pradesh                          42
Tamil Nadu                             34
Karnataka                              32
National Capital Territory of Delhi    32
Kerala                                 26
Andhra Pradesh                         23
Madhya Pradesh                         22
Rajasthan                              14
Himachal Pradesh                       10
Manipur                                10
Gujarat                                 9
Bihar                                   6
Jharkhand                               5
Assam                                   5
Jammu and Kashmir                       5
Uttarakhand                             4
Tripura                                 3
Chhattisgarh                            2
Chandigarh                              2
Goa                                     2
Nagaland                                2
Mizoram                                 1
Puducherry                              1
Sikkim                                  1
Orissa                                  1
Name: count, dtype: int64

In [9]:
coffee=pd.read_csv('./data/coffee.csv')

In [12]:
coffee.groupby(["Coffee Type"])["Units Sold"].sum()

Coffee Type
Espresso    265.0
Latte       195.0
Name: Units Sold, dtype: float64

In [13]:
coffee.groupby(["Coffee Type"]).agg({'Units Sold':'sum','price':'mean'})

             Units Sold  price
Coffee Type
Espresso          265.0   3.99
Latte             195.0   6.33

In [15]:
pivot=coffee.pivot(columns='Coffee Type',index='Day',values='revenue')

In [16]:
pivot

Coffee Type   NaN  Espresso   Latte
Day
1            63.3       NaN     NaN
Friday        NaN    179.55  221.55
Monday        NaN     99.75   94.95
Saturday      NaN    179.55  221.55
Sunday        NaN    179.55  221.55
Thursday      NaN    159.60  189.90
Tuesday       NaN    119.70  126.60
Wednesday     NaN    139.65  158.25

In [18]:
pivot.loc['Monday','Latte']

np.float64(94.95)

In [19]:
pivot.sum()

Coffee Type
NaN           63.30
Espresso    1057.35
Latte       1234.35
dtype: float64

In [20]:
bios['born_date']=pd.to_datetime(bios['born_date'])

In [22]:
bios.groupby(bios['born_date'].dt.year)['name'].count()

born_date
1828.0      1
1831.0      2
1833.0      1
1836.0      1
1837.0      1
         ...
2005.0    163
2006.0     17
2007.0      3
2008.0      3
2009.0      1
Name: name, Length: 177, dtype: int64

In [23]:
bios.groupby(bios['born_date'].dt.year)['name'].count().reset_index().sort_values('name',ascending=False)

     born_date  name
139     1972.0  2231
152     1985.0  2227
140     1973.0  2216
138     1971.0  2205
137     1970.0  2174
..         ...   ...
4       1837.0     1
2       1833.0     1
6       1839.0     1
12      1845.0     1
176     2009.0     1

[177 rows x 2 columns]

## Advanced Fuctionality

In [26]:
coffee['yesterdays_revenue']=coffee['revenue'].shift(2)

In [27]:
coffee

,Day,Day.1,Coffee Type,Units Sold,price,revenue,price.1,yesterdays_revenue
0,Monday,Monday,Espresso,25.0,3.99,99.75,3.99,NaN
1,Monday,Monday,Latte,15.0,6.33,94.95,6.33,NaN
2,Tuesday,Tuesday,Espresso,30.0,3.99,119.70,3.99,99.75
3,Tuesday,Tuesday,Latte,20.0,6.33,126.60,6.33,94.95
4,Wednesday,Wednesday,Espresso,35.0,3.99,139.65,3.99,119.70
5,Wednesday,Wednesday,Latte,25.0,6.33,158.25,6.33,126.60
6,Thursday,Thursday,Espresso,40.0,3.99,159.60,3.99,139.65
7,Thursday,Thursday,Latte,30.0,6.33,189.90,6.33,158.25
8,Friday,Friday,Espresso,45.0,3.99,179.55,3.99,159.60
9,Friday,Friday,Latte,35.0,6.33,221.55,6.33,189.90
10,Saturday,Saturday,Espresso,45.0,3.99,179.55,3.99,179.55
11,Saturday,Saturday,Latte,35.0,6.33,221.55,6.33,221.55
12,Sunday,Sunday,Espresso,45.0,3.99,179.55,3.99,179.55
13,Sunday,Sunday,Latte,35.0,6.33,221.55,6.33,221.55
14,1,NaN,NaN,10.0,6.33,63.30,6.33,179.55

In [28]:
coffee['pct_change']=coffee['revenue']/coffee['yesterdays_revenue']*100

In [29]:
coffee

,Day,Day.1,Coffee Type,Units Sold,price,revenue,price.1,yesterdays_revenue,pct_change
0,Monday,Monday,Espresso,25.0,3.99,99.75,3.99,NaN,NaN
1,Monday,Monday,Latte,15.0,6.33,94.95,6.33,NaN,NaN
2,Tuesday,Tuesday,Espresso,30.0,3.99,119.70,3.99,99.75,120.000000
3,Tuesday,Tuesday,Latte,20.0,6.33,126.60,6.33,94.95,133.333333
4,Wednesday,Wednesday,Espresso,35.0,3.99,139.65,3.99,119.70,116.666667
5,Wednesday,Wednesday,Latte,25.0,6.33,158.25,6.33,126.60,125.000000
6,Thursday,Thursday,Espresso,40.0,3.99,159.60,3.99,139.65,114.285714
7,Thursday,Thursday,Latte,30.0,6.33,189.90,6.33,158.25,120.000000
8,Friday,Friday,Espresso,45.0,3.99,179.55,3.99,159.60,112.500000
9,Friday,Friday,Latte,35.0,6.33,221.55,6.33,189.90,116.666667
10,Saturday,Saturday,Espresso,45.0,3.99,179.55,3.99,179.55,100.000000
11,Saturday,Saturday,Latte,35.0,6.33,221.55,6.33,221.55,100.000000
12,Sunday,Sunday,Espresso,45.0,3.99,179.55,3.99,179.55,100.000000
13,Sunday,Sunday,Latte,35.0,6.33,221.55,6.33,221.55,100.000000
14,1,NaN,NaN,10.0,6.33,63.30,6.33,179.55,35.254804

In [31]:
bios['height_rank']=bios['height_cm'].rank(ascending=False)

In [32]:
bios.sort_values(['height_rank'],ascending=False)

,Unnamed: 0.1,Unnamed: 0,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,hight_rank,height_rank
28619,28619,28619,28832,Rosario Briones,1953-10-05,San Luis Potosí,San Luis Potosí,MEX,Mexico,127.0,42.0,NaN,Rosario,106650.5,106650.5
4515,4515,4515,4530,Lyton Mphande,1963-05-14,NaN,NaN,NaN,Malawi,127.0,62.0,NaN,Lyton,106650.5,106650.5
4516,4516,4516,4531,Helman Palije,1967-06-24,NaN,NaN,NaN,Malawi,128.0,74.0,NaN,Helman,106649.0,106649.0
4664,4664,4664,4681,Salvador Miranda,1949-09-13,NaN,NaN,NaN,Nicaragua,130.0,51.0,NaN,Salvador,106647.5,106647.5
4517,4517,4517,4532,Boston Simbeye,1959-12-24,NaN,NaN,NaN,Malawi,130.0,67.0,NaN,Boston,106647.5,106647.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145490,145490,145490,149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN,Sin,NaN,NaN
145491,145491,145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN,Matthew,NaN,NaN
145492,145492,145492,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,Carlos,NaN,NaN
145493,145493,145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,Landysh,NaN,NaN
145499,145499,145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,NaN,NaN

In [33]:
coffee['cumulitive_revenue']=coffee['revenue'].cumsum()

In [34]:
coffee

,Day,Day.1,Coffee Type,Units Sold,price,revenue,price.1,yesterdays_revenue,pct_change,cumulitive_revenue
0,Monday,Monday,Espresso,25.0,3.99,99.75,3.99,NaN,NaN,99.75
1,Monday,Monday,Latte,15.0,6.33,94.95,6.33,NaN,NaN,194.70
2,Tuesday,Tuesday,Espresso,30.0,3.99,119.70,3.99,99.75,120.000000,314.40
3,Tuesday,Tuesday,Latte,20.0,6.33,126.60,6.33,94.95,133.333333,441.00
4,Wednesday,Wednesday,Espresso,35.0,3.99,139.65,3.99,119.70,116.666667,580.65
5,Wednesday,Wednesday,Latte,25.0,6.33,158.25,6.33,126.60,125.000000,738.90
6,Thursday,Thursday,Espresso,40.0,3.99,159.60,3.99,139.65,114.285714,898.50
7,Thursday,Thursday,Latte,30.0,6.33,189.90,6.33,158.25,120.000000,1088.40
8,Friday,Friday,Espresso,45.0,3.99,179.55,3.99,159.60,112.500000,1267.95
9,Friday,Friday,Latte,35.0,6.33,221.55,6.33,189.90,116.666667,1489.50
10,Saturday,Saturday,Espresso,45.0,3.99,179.55,3.99,179.55,100.000000,1669.05
11,Saturday,Saturday,Latte,35.0,6.33,221.55,6.33,221.55,100.000000,1890.60
12,Sunday,Sunday,Espresso,45.0,3.99,179.55,3.99,179.55,100.000000,2070.15
13,Sunday,Sunday,Latte,35.0,6.33,221.55,6.33,221.55,100.000000,2291.70
14,1,NaN,NaN,10.0,6.33,63.30,6.33,179.55,35.254804,2355.00

In [35]:
latte=coffee[coffee['Coffee Type']=="Latte"].copy()
latte['3days']=latte['Units Sold'].rolling(3).sum()

In [36]:
latte

,Day,Day.1,Coffee Type,Units Sold,price,revenue,price.1,yesterdays_revenue,pct_change,cumulitive_revenue,3days
1,Monday,Monday,Latte,15.0,6.33,94.95,6.33,NaN,NaN,194.7,NaN
3,Tuesday,Tuesday,Latte,20.0,6.33,126.60,6.33,94.95,133.333333,441.0,NaN
5,Wednesday,Wednesday,Latte,25.0,6.33,158.25,6.33,126.60,125.000000,738.9,60.0
7,Thursday,Thursday,Latte,30.0,6.33,189.90,6.33,158.25,120.000000,1088.4,75.0
9,Friday,Friday,Latte,35.0,6.33,221.55,6.33,189.90,116.666667,1489.5,90.0
11,Saturday,Saturday,Latte,35.0,6.33,221.55,6.33,221.55,100.000000,1890.6,100.0
13,Sunday,Sunday,Latte,35.0,6.33,221.55,6.33,221.55,100.000000,2291.7,105.0